### ISSUE TITLE
(bug) querying words with a dash, color or semicolon leads to error

### ISSUE THREAD

**Issue by Maztermo** [ordbokapi/api#70]
If the search query contains either
"-" a dash 
":" a colon
";" a semicolon

The api seems to return an internal error.

## How to reproduce bug in [apollo](https://api.ordbokapi.org/graphql) :

```
query Query($word: String!) {
  word(word: $word) {
    word
  }
}
```

or

```
query Query($word: String!) {
  suggestions(word: $word) {
    exact {
      word
    }
  }
}
```

with variables set to
```
{
  "word": "hakke"         //  ✅
  "word": "hakkespett"    //  ✅
  "word": "hakke-spett"   //  ❌
  "word": "hakkespett:"   //  ❌
  "word": "hakkespett;"   //  ❌
}
```
Havent tested other symbols extensively, but period ( . ) and comma ( , ) seem to go through just fine.

**Comment by adalinesimonian** [comment]
Fiksa i d4be6a3. [Døme](https://api.ordbokapi.org/graphql?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAIq6EAUAJAO4R5jpEDKKeAlkgOYCEAlEWAAdPEKREidBhSmMitemAHDR4iZMUix6ogEM8KdlAA2CAM6CtanezBWdEsEcMQk%2BgvYem4cXRZXaDhLevp46AL5hRJGqEjFi4SAANCAAbvrsugBGpmYYIAFqQiCyxUzF7ADWlQBWCAC0WZwAZ6IgVonhQA)
